- azure-pipelines.yml
- build/Invoke-CollectionTests.ps1
- build/Publish-Collection.ps1
- chocolatey/galaxy.yml
This configuration is sufficient for publishing to Galaxy. Additional variables need to be defined in the pipeline for AH publishing.
Currently this publish will trigger when a commit is tagged in the repo.
> Setup the pipeline for publishing to Galaxy and AH

- chocolatey/plugins/modules/win_chocolatey.ps1
Previously the Uninstall would add the incorrect argument.
Without this change the uninstall script will not function properly
with the package_params argument
Fixes #8
> (GH-8) Fix invalid argument assignment

- azure-pipelines.yml
- build/Publish-Collection.ps1
- build/ansible.cfg
Reworked pipeline using documentation from Ansible around publishing:
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#galaxy-server-config
- Added `ansible.cfg` with some placeholder values for API keys
- Added step to publishing pipeline to create an `ansible.cfg` file before publishing, using the template file and replacing the placeholder values with Azure Pipelines variables (already configured via Azure DevOps Pipelines).
- Consolidated the two publishing steps into a single step which should publish to both servers (if I'm reading documentation correctly).
> Rework pipeline for AH/Galaxy publishing

- chocolatey/galaxy.yml
Adds support for installing this collection as a git repo source based on the changes in https://github.com/ansible/ansible/pull/69154.
The changes proposed in the PR 69154 requires the `galaxy.yml` in the git repo to be valid yaml. Having these quotes will allow people to install this collection for unpublished builds for local testing or development if that is desired.
> Quote replacement yaml text for git installs

- azure-pipelines.yml
This change lets us timestamp the VM names we're using so that Azure's plugins don't find a VM being used by a different PR if they happen to be filed / updated at similar times.
The VM name limit is 15 chars, so we basically only have room for the timestamp and nothing more. c'est la vie.
EDIT: They're _very_ picky about their VM names, apparently. Think I got it sorted for now though.
> Add timestamp to VM name

- build/Invoke-CollectionTests.ps1
- chocolatey/plugins/modules/win_chocolatey.py
- chocolatey/plugins/modules/win_chocolatey_config.py
- chocolatey/plugins/modules/win_chocolatey_facts.py
- chocolatey/plugins/modules/win_chocolatey_feature.py
- chocolatey/plugins/modules/win_chocolatey_source.py
Fixing some linting issues I saw in recent CI runs. Fixes #30.
- Rewrite old versions to 0.x.x so they match semver and kind of make sense for the current version of the modules being 1.x.
- Fix doc argument spec issues.
> (#30) Fix doc linting issues

- chocolatey/plugins/modules/win_chocolatey_config.ps1
- chocolatey/plugins/modules/win_chocolatey_facts.ps1
- chocolatey/plugins/modules/win_chocolatey_feature.ps1
- chocolatey/plugins/modules/win_chocolatey_source.ps1
Due to an issue in Win32-OpenSSH (see PowerShell/Win32-OpenSSH#1329) a fallback is necessary in all of these plugins, as the environment variables will not be updated after installing choco until the SSHD session is restarted or the system is rebooted.
This PR adds a similar fallback to the other plugins that already exists in `win_chocolatey` where it will fall back to the default install path.
As the installation method used in win_chocolatey doesn't currently allow for Chocolatey to be installed to a non-default path this workaround should be sufficient for the time being. It can be revisited in future if we modify the Chocolatey installation behaviour to allow users to specify where Chocolatey is installed to.
Resolves #22
> (#22) Fallback to default choco path

- build/dependencies.sh
- chocolatey/plugins/modules/win_chocolatey.ps1
- chocolatey/tests/integration/targets/win_chocolatey/tasks/tests.yml
This is a workaround for chocolatey/choco#2101. 
On uninstall, we can't use `--allow-multiple` unilaterally; it breaks the uninstall when there is only a single package version installed.
So there are now two states, neither of which should be exposed as configurable in my opinion, because it would simply allow users to break things, and not give them any utility. `allow_multiple:` from Ansible will still be ignored completely for `state: absent` requests, and the module will apply it as is required.
Basically, the flow is now this (for `state: absent` specifically):
1. If there are multiple package versions installed:
a. If a specific version is NOT specified, do not pass `--allow-multiple` either, and choco will uninstall all versions of the package that are currently installed.
b. If a …
> (#21) :bug: Remove --allow-multiple for uninstall

- build/dependencies.sh
- chocolatey/plugins/modules/win_chocolatey.ps1
- chocolatey/tests/integration/targets/win_chocolatey/tasks/tests.yml
Previously, specifying a direct version would have choco error out with either `state: absent` or `state: reinstalled` if that specific version isn't actually installed, which we don't want.
Fixed by allowing the version value provided to be passed through to the choco list command, which will allow us to filter down to only target installed _versions_ of packages, if desired.
When `state:absent` is supplied along with a target version, module will no-op when that version is not already installed.
Fixes #35
> (#35) Fix state:absent for specific versions

- chocolatey/plugins/modules/win_chocolatey.ps1
Two main improvements have been made in this PR:
1. When checking the URL ends with `.ps1`, make sure we use a non-case-sensitive check (i.e., a URL of the form `https://server.com/example/chocolatey.PS1` should still work.
2. If it doesn't end in PS1, look for known patterns in the URL, like the common Nexus pattern of `/repository/*` which indicates the script should look in a specific repository, rather than just assuming the script is definitely hosted in the server root.
This resolves #18 at least for some of the common cases. We can add more complex handling here if needed in future.
> (#18) Use more versatile URL handling for getting the chocolatey install script URL

- .gitignore
- testing-chocolatey/Vagrantfile
- testing-chocolatey/local-testing.md
This adds a Vagrantfile w/ instructions to allow local testing of new versions of Chocolatey via the Ansible collection.
The purpose of this is to allow us to double-check new Chocolatey beta versions to ensure that there is no critical functionality missing from the Ansible collection, as well as ensuring that new Chocolatey versions don't break any existing critical functionality.
I've provided some more generic instruction as well so we have a documented way to setup the servers directly if we want to do it without the Vagrantfile.
> Add files for locally testing Chocolatey itself using the collection

- chocolatey/meta/runtime.yml
Ansible collections should define a minimum Ansible versions in a meta/runtime.yml file in the collection directory.
This PR adds the file and sets the minimum Ansible version to 2.9.0, in keeping with most collections and recommendations from Ansible folks who know much better than I do ;)
Fixes #45
> Add runtime.yml

- chocolatey/tests/integration/targets/win_chocolatey_facts/tasks/main.yml
- chocolatey/tests/integration/targets/win_chocolatey_source/tasks/main.yml
The win_chocolatey_source tests re-added the default source with a capital C in the name, which doesn't match the normal default (all lowercase).
This causes other tests to fail on a rerun, as the source name is now different than expected.
Fix is to ensure we re-add the source name in lowercase.
This should also allow us to test against multiple Ansible versions, reusing the same Windows VM for all the integration tests before destroying it.
Fixes #47
> Fix win_chocolatey_source tests to allow for test reruns to work correctly

- azure-pipelines.yml
- build/Invoke-CollectionTests.ps1
- build/Vagrantfile
- build/dependencies.sh
- chocolatey/plugins/modules/win_chocolatey_facts.py
- chocolatey/tests/integration/targets/win_chocolatey_facts/tasks/main.yml
- chocolatey/tests/integration/targets/win_chocolatey_source/tasks/main.yml
- chocolatey/tests/integration/targets/win_chocolatey_source/tasks/tests.yml
Update the CI/CD to ensure we're testing against:
- Ansible 2.9
- Ansible-Base 2.10
- Ansible-Core 2.11
- Ansible-Core 2.12.x (latest version)
- Closes #57
- Closes #64
We need to be testing on current and a few older versions of Ansible to remain certified, so updating this build pipeline will keep things going there, and give us a better idea of when things break, if anything happens to break only on specific Ansible versions.
Thanks to using an azp matrix strategy, we can add any future versions as needed as well.
I am also resolving #64 here in a separate commit as it was getting tripped up over those tests.
> (#57) Update CI/CD to test against multiple Ansible versions

- build/Invoke-CollectionTests.ps1
- build/Vagrantfile
- build/dependencies.sh
- build/vagrant-dependencies.sh
- chocolatey/plugins/modules/win_chocolatey.ps1
- chocolatey/plugins/modules/win_chocolatey.py
- chocolatey/plugins/modules/win_chocolatey_source.ps1
- chocolatey/plugins/modules/win_chocolatey_source.py
- chocolatey/tests/integration/targets/win_chocolatey/tasks/tests.yml
- Added `upgrade` state value as a valid option for `win_chocolatey`.
- Updated tests to also test this new state value.
- Updated py docs to make it a bit clearer why things can fail with `state: present` if a specific version is targeted
See #59 -- our documentation and the commands necessary do not always make it clear that `state: latest` is required for certain usage patterns, especially when combined with `version:` to specify a target version.
This PR adds a `state: upgrade` as a more intuitive alias to the existing `state: latest` to better mirror the also existing `state: downgrade` and be a little clearer.
The py documentation has been updated a little to explain a little more of why playbooks that target a specific version with `state: present` may fail instead of …
> Add state: upgrade as more intuitive alias for state: latest

- chocolatey/plugins/modules/win_chocolatey.ps1
- chocolatey/plugins/modules/win_chocolatey.py
- chocolatey/tests/integration/targets/win_chocolatey/tasks/tests.yml
- Added `choco_args` option (aliased also to `licensed_args`) that allows users to manually pass in a list of args to be passed directly to choco itself.
- Updated py docs
- Added a test for the new option
This allows users to specify arguments that are not explicity supported by the collection, for example any options that require the chocolatey licensed extension to be installed.
This also gives us a workaround / stop-gap for any additional arguments in open source Chocolatey in future, allowing users to specify them manually until the collection is updated to include those options.
Added a CI test that replicates one of the existing installer tests, with the arguments being manually passed in via the new options, instead of using the typical installation options.
NOTE: We do not …
> (#15) Allow additional choco args to be passed manually

- README.md
- build/dependencies.sh
- build/vagrant-dependencies.sh
- chocolatey/requirements.txt
Added `requirements.txt` file for our Python dependencies that help handle the remoting layer to Windows.
Removed the explicit install commands for these dependencies 
It's a good idea to declare the dependencies of the collection so they're more discoverable and can be automatically taken care of, and it's one of the requirements of the collection being/remaining certified (if I understand the documentation correctly).
1. Ran the test script locally, things seemed to install just fine and run without issue, even without explicitly installing. (Note: still seeing the issue locally with loading certain ansible.windows modules from #71, so I'm reopening that issue presently)
2. Running in CI to double check. Looking at the CI logs for the start of the test runs show Ansible downloading …
> (#61) Add requirements.txt file and update readme

- azure-pipelines.yml
- chocolatey/plugins/module_utils/Common.psm1
- chocolatey/plugins/module_utils/Features.psm1
- chocolatey/plugins/module_utils/Packages.psm1
- chocolatey/plugins/module_utils/Sources.psm1
- chocolatey/plugins/modules/win_chocolatey.ps1
- chocolatey/plugins/modules/win_chocolatey.py
- chocolatey/plugins/modules/win_chocolatey_config.ps1
- chocolatey/plugins/modules/win_chocolatey_facts.ps1
- chocolatey/plugins/modules/win_chocolatey_facts.py
- chocolatey/plugins/modules/win_chocolatey_feature.ps1
- chocolatey/plugins/modules/win_chocolatey_source.ps1
- chocolatey/tests/integration/targets/setup_win_chocolatey/files/tools/chocolateyinstall.ps1
- chocolatey/tests/integration/targets/win_chocolatey_source/library/choco_source.ps1
- Renamed some internal PowerShell commands to conform to PSSA style requirements
- Added missing `process` block for a pipeline command
- Went through and removed unnecessary whitespace.
- Note: for module spec hashtables which tend to be complex, opted to instead suppress the PSSA rule there as it can be more readable to pad spacing a bit to better indicate which items belong to which hashtable in the nested structure(s).
- Split some long error messages into separate lines
- Added FQCN (fully qualified collection name... I think?) to all `M()` module references used in the modules' documentation and `seealso` sections.
- Added ansible-core 2.12 to test targets since latest is now 2.13
`ansible-core` 2.13 has improved the linting a good bit, and we need to conform a little better to the …
> (#78) Fix module linting issues

- testing-chocolatey/Vagrantfile
Update the Vagrantfile in the `testing-chocolatey` directory to install PowerShell so that sanity tests can be run in it.
Need the ability to test all aspects of the collection.
1. Copy a build from Azure DevOps into the `testing-chocolatey` directory
2. In the `testing-chocolatey` directory ran `vagrant up`
3. Run `vagrant ssh choco_ansible_server`
4. Run `source ~/ansible/bin/activate`
5. Run `ansible-galaxy collection install /vagrant/chocolatey-chocolatey.tar.gz`
6. Run `ansible-test sanity --requirements` (Note: `--requirements` is needed of PSScriptAnalyzer is not available)
7. The tests pass
Fixes #84
> (#84) Update testing Vagrantfile to install PowerShell

- chocolatey/plugins/modules/win_chocolatey.ps1
- chocolatey/tests/integration/targets/win_chocolatey/tasks/tests.yml
* Added `Where-Object` filter to `packageVersions` declaration when attempting to install a specific version of a package to remove null or empty entries.
Previously null entries weren't being filtered. This caused failures when attempting to install a specific version of a package since packageVersions.Count would unexpectedly be greater than 0.
1. Exploratory testing of the proposed changes
1. Ran integration tests locally
Fixes #91
> (#91) Filter null entries from packageVersions

- chocolatey/plugins/modules/win_chocolatey.ps1
- Remove usage of `::new()` in `win_chocolatey.ps1`
Ansible supports PowerShell down to v3, and this collection should as well so we don't get parse errors when running module tasks.
1. Test in CI, this is a tiny change.
Fixes #92
> (#92) Remove usage of ::new for PS compatibility

- chocolatey/plugins/module_utils/Packages.psm1
- chocolatey/tests/integration/targets/win_chocolatey/tasks/tests.yml
- Handle null case and emit proper warning when looking for Chocolatey install version
If the chocolatey package files are missing from the client machine, we will not be able to determine the version.
Ensure we handle the null case here and emit a (somewhat) useful warning.
1. Added test to ensure if anyone has nodes in this state that installs/upgrades still work as expected.
2. Running tests in CI
Fixes #90
> (#90) Avoid indexing null array

- chocolatey/tests/integration/vagrant-inventory.winrm
- testing-chocolatey/Vagrantfile
- testing-chocolatey/local-testing.md
Fix ntlm related errors when running the test environment on an OS that no longer supports md4. Also migrate away from the 'StefanScherer/windows_10' box as that box starts 'Windows Update' when Vagrant is still running. This happens when the box is created outside of normal office hours.
I had some problems with the test environment of this repo on my Fedora laptop when I was working on https://github.com/chocolatey/chocolatey-ansible/pull/81.
When running vagrant up in the testing-chocolatey directory I got:
```
An error occurred executing a remote WinRM command.
Shell: Cmd
Command: hostname
Message: Digest initialization failed: initialization error
```
After some manual changes I got the servers running. I then got errors running the ansible-test command as describe in the …
> (#83) Fix issues with Linux host in local testing

- build/Vagrantfile
- build/vagrant-dependencies.sh
- chocolatey/requirements.txt
- chocolatey/tests/integration/targets/win_chocolatey/tasks/tests.yml
- Remove `pyOpenSSL` requirement from the collection.
- Also small fix copied over from the 'local testing' vagrantfile to the vagrantfile used by Invoke-ColletionTests.ps1 that got that working again for me locally, and a small change to vagrant-dependencies.sh that made the tests all work correctly again so I was able to test it locally as well.
Remove workaround for an issue in ansible-test that has since been fixed. This was only ever necessary due to an issue in a specific version of ansible-test that clashed with a version of pyOpenSSL and a change that was made in v22 of pyOpenSSL. I believe this issue should be resolved by now, so we should be OK to remove this and see if anything breaks.
1. Testing in CI to ensure we test against all the ansible versions we need to be testing …
> (maint) Remove pyopenssl requirement

- .gitignore
- README.md
- azure-pipelines.yml
- build/Invoke-CollectionTests.ps1
- build/README.md
- build/Start-VagrantEnvironment.ps1
- build/Vagrantfile
- build/azure/Set-AzLabVMParams.ps1
- build/vagrant-dependencies.sh
- Update some things in the Vagrant setup, adds a new Vagrant setup script to prep an environment for easy interactive fiddling with the collection and Ansible.
- Updated the CI infra to use CredSSP as there are issues with using NTLM in the newer Ubuntu Azure Pipelines agents. Something about OpenSSL no longer natively providing MD4 hashing or something, I'm not super clear why. But using CredSSP avoids this issue without us having to add an extra dependency to our CI runs.
- Remove EOL'd Ansible-core versions from CI runs, and added specific runs for 2.13 and 2.14 as those are both released.
While doing #109, I noticed that CI was not functioning properly, no test results were coming back.
Ansible lists 2.9, 2.10, and 2.11 as `EOL`, so we should probably similarly remove them from CI …
> (maint) Update CI to fix some issues getting tests to run properly, remove EOL'd ansible-core test runs

- azure-pipelines.yml
- build/Invoke-CollectionTests.ps1
- build/Start-VagrantEnvironment.ps1
- chocolatey/meta/runtime.yml
- chocolatey/plugins/modules/win_chocolatey.ps1
- chocolatey/plugins/modules/win_chocolatey.py
- Deprecated the allow_multiple feature and add some info to the documentation entry for it as well
See #94
Make a new `playbook.yml` file in the `build/vagrant-files` directory with the following content:
```yaml
---
- name: Test allow_multiple deprecation warnings
gather_facts: false
hosts: all
tasks:
- name: Install a package with allow_multiple
chocolatey.chocolatey.win_chocolatey:
name: python
version: 3.9.5
allow_multiple: yes
state: present
```
Follow the instructions in `build/README.md` and use `Start-VagrantEnvironment.ps1` to get the Vagrant environment up and running, and run the above playbook with `ansible-playbook`.
You should see a prominent deprecation warning displayed like so:
```
[DEPRECATION WARNING]: Param 'allow_multiple' is deprecated. See the module docs for more …
```
> win_chocolatey - Deprecate `allow_multiple` option

- README.md
- azure-pipelines.yml
- Add Ansible-core 2.15 to the testing matrix
- Remove Ansible-core 2.12 from the testing matrix
- Fix pip package version specifiers, not sure how long _that's_ been there
Ansible 2.12 was EOL'd in May, and Ansible 2.15 is the current stable version.
Testing in CI
N/A
N/A, maint only
> (maint) Update ansible-core versions tested

- chocolatey/plugins/module_utils/Packages.psm1
- chocolatey/plugins/modules/win_chocolatey.ps1
- chocolatey/plugins/modules/win_chocolatey.py
- chocolatey/tests/integration/targets/setup_win_chocolatey/files/test-package/tools/chocolateyinstall.ps1
- chocolatey/tests/integration/targets/win_chocolatey/tasks/tests.yml
- Add options to win_chocolatey to allow the user to specify the checksum and type for package installs
Allow users to specify the checksum and type to be used for package installs and upgrades.
- CI tests added
- Can be tested in the local vagrant env by attempting a normal package install of something that requires downloading the installer (googlechrome, firefox, etc), and then attempting again while overriding the checksums or the checksum types with junk data and watching it crash and burn :3
Win10
Fixes #114
> (#114) Add checksum options

- chocolatey/plugins/modules/win_chocolatey_facts.ps1
- chocolatey/plugins/modules/win_chocolatey_facts.py
- chocolatey/tests/integration/targets/win_chocolatey_facts/tasks/main.yml
- chocolatey/tests/integration/targets/win_chocolatey_facts/tasks/test_gather_facts.yml
This PR adds a `gather_subset` parameter to the win_chocolatey_facts module which allows the user to "gather" only a subset of facts.
Currently the win_chocolatey_facts module gets ALL facts available to it, including:
- All config settings
- All features
- Sources
- Installed packages
- Outdated packages
This means there is a lot of information being complied even if the user doesn't need it. This can be especially egregious when pulling the outdated packages when the target has a large number of packages installed.
`gather_subset` is an established pattern when gathering general Ansible facts, see [Gathers facts about remote hosts](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html#parameter-gather_subset), and the implementation in this module …
> (108) Add filter parameter to win_chocolatey_facts module

- chocolatey/plugins/module_utils/Packages.psm1
This PR ensures that the `Get-ChocolateyVersion` function only attempts to cast the Chocolatey CLI version number as a `version` object.
To achieve this the `stdout` from executing `choco --version` is matches against the [recommended regular expression](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) for checking SemVer strings.
When a Chocolatey for Business or Pro license is installed on a system but the licensed extension package is not yet installed, additional information is presented to the user.
This pollutes the `stdout` stream meaning that it is not possible to directly cast the information on this stream and a `version` object.
Instead, the stream is matched against a regular expression representing a valid SemVer string, and then the …
> (#132) Ensure only Chocolatey CLI version number is processed through Get-ChocolateyVersion function

- build/azure/client-template.json
- build/dependencies.sh
- build/vagrant-dependencies.sh
- chocolatey/tests/requirements.txt
This MR bumps the required Jinja2 version used in the build and test pipelines to `~>3.1.3` (and version from 3.1.3 through 3.1.x)
Versions of Jinja2 below 3.1.3 are affected by [CVE-2024-22195](https://access.redhat.com/security/cve/cve-2024-22195)
This MR also updates the Azure Windows Client image used in the Azure Pipeline as the previous one had been removed.
This change has been exercised through the Azure Pipeline and resulted in a successful build and test.
N/A
Build change
~~* [ ] Bug fix (non-breaking change).~~
~~* [ ] Feature / Enhancement (non-breaking change).~~
~~* [ ] Breaking change (fix or feature that could cause existing functionality to change).~~
~~* [ ] Documentation changes.~~
~~* [ ] PowerShell code changes.~~
~~* [ ] Requires a change to the documentation.~~
~~* …
> (build) Bump required Jinja2 version for build and test pipelines

- chocolatey/plugins/modules/win_chocolatey.py
Improve user documentation of the `timeout` parameter by explaining the unit.
It took me a while to verify the value actually means `seconds` and not something else, this should be easy to improve for other users.
N/A
N/A
Fixes #138
> Add hint about the timeout unit

- chocolatey/plugins/module_utils/Common.psm1
- chocolatey/plugins/modules/win_chocolatey.py
When for some reason the path environment variable contains two installations of chocolatey this function will return a list, which causes a syntax error down the line. Since running choco.exe on the machine will also choose the first installation in the path, I think limiting the found installations to the first is the desired behavior here.
Restricted the output of Get-Command to the first finding
I encountered a crashing win_chocolatey task, when on the target machine the path variable contained multiple choco installations. Limiting the finding to the first in the PATH, the same way it would be resolved in the powershell on the machine, fixes this problem. 
I have tried this out before and after the change, the change fixes this issue
- Windows 10
- Windows 11
Fixes #147
> Fix crashing when PATH contains multiple choco installations

- chocolatey/meta/runtime.yml
- Update the `requires_ansible` metadata
RedHat are requiring this match their minimum supported ansible-core version in order to publish to Automation Hub.
Metadata change only, I'm not sure what we can do to make sure this is tested going forward?
I've looked through [Ansible's testing documentation](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_testing.html) and I'm not seeing anything that talks about a test that will verify this. We are running their `sanity` tests already, and it doesn't seem to check this for us.
N/A
Fixes #164
> (#164) Update requires_ansible to >=2.15.0

- README.md
- azure-pipelines.yml
- chocolatey/meta/runtime.yml
- Set colleciton minimum ansible-core version to 2.16, the current lowest version that is still supported
- Update CI testing to test 2.16-2.18
- Build collection on 2.18 of ansible-core
- Update readme
We need to keep in-step with Ansible's supported versions of ansible-core and ensure we're testing appropriately.
Running tests in CI from the PR
N/A
Fixes #169
> (#169) Update ansible-core versions supported/tested

- README.md
- azure-pipelines.yml
- build/dependencies.sh
- Added 2.19 to the ansible-core versions we're explicitly testing
- Updated the ansible version used to *build* the collection to 2.18 (latest current stable according to [the lifecycle page](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix)
- Also, updated an outdated link in the README that was being used for the pipeline status badge.
- Amended the `dependencies.sh` script to allow `pip3` to pull in a prerelease version for `ansible-core` with no version specified, so it pulls the actual latest, and a matching pipeline configuration that calls for a prerelease version.
See #177; we need this testing to be explicitly done to validate compatibility and ensure inclusion with the community package shipped with Ansible …
> (#177) Ensure we're testing against Ansible 2.19

- azure-pipelines.yml
- Use `~=` "compatible version" specifiers instead of exact version requirements in our CI.
Previously we used `==` which would not match newer patch versions (so `==2.18` would only match `2.18.0`), which means we didn't test on the latest available patch for that release version.
Per https://packaging.python.org/en/latest/specifications/version-specifiers/#id5 we can use `~=X.X.0` to take the latest patch version of `X.X` release.
This fixes the problem where certain `X.X.0` versions of ansible-core are not always available and we still test against that minor version correctly. This hasn't happened recently but we should ensure our CI is testing on the latest patch versions for each minor version.
CI testing runs, we should get the latest available patch version for each ansible-core …
> (maint) Use latest patch version of ansible-core in CI
